### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by li512871889** [Alina-1997/visual-distortion-in-attack#10]
李博士您好，我对您之前发表的一篇关于元学习结合图像描述的一篇论文很有兴趣，课题组也想进行进一步的研究，但对其中的一些细节不太清楚，请问您方便提供一下代码吗

**Comment by NannanLi999** [comment]
那篇论文的代码没有整合和整理，所以并不公开。具体细节可以参考 https://github.com/cbfinn/maml
