### ISSUE TITLE
Outer iteration makes comparison unfair

### ISSUE THREAD

**Issue by Daizy97** [Alina-1997/visual-distortion-in-attack#9]
`for outer_i in range(self.outer_iterations):`
In black_box_attack.py, line 218, there is an outer iteration out of the normal 10000 iterations. It seems as long as an example succeeds in one of 5 outer iterations, it will be recorded as successful. I don't think it is fair to be compared with other attacks which only use 10000 iterations.

**Comment by NannanLi999** [comment]
We use outer_iteraions because the random initialization of model affects the results. So, we pick the best attack in 5 runs, which can be regarded as a way of model ensemble. Simply setting outer_iteraions to be 1 can show you the results without model ensemble.
